export const APP_ROUTES = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  NOT_FOUND: 'NOT_FOUND',
  SERVER_ERROR: 'SERVER_ERROR',
  CHAT: 'CHAT',
  CHAT_PROFILE: 'PROFILE',
  CHAT_DIALOG: 'DIALOG',
  CHAT_CHANGE_DATA: 'CHANGE_DATA',
  CHAT_CHANGE_PASSWORD: 'CHANGE_PASSWORD',
};
