export const INTL = {
  TITLE: 'Sign up',
  EMAIL: {
    LABLE: 'Email',
    TYPE: 'email',
    NAME: 'email',
    PLACEHOLDER: 'Enter email',
    PATTERN: '^[^\s@]+@[^\s@]+\.[^@]{2,}$',
    TITLE: 'Неверный формат email',
  },
  LOGIN: {
    LABLE: 'Login',
    TYPE: 'text',
    NAME: 'login',
    PLACEHOLDER: 'Enter login',
    PATTERN: '^(?=.*[a-zA-Z])(?!.*\d{3,20}$)[a-zA-Z\d_-]{3,20}$',
    TITLE: 'Текст должен содержать только буквы и дефисы',
  },
  FIRST_NAME: {
    LABLE: 'Firs name',
    TYPE: 'text',
    NAME: 'first_name',
    PLACEHOLDER: 'Enter first name',
    PATTERN: '^[A-Z\u0410-\u042F\u0401][\w\u0410-\u042F\u0401\u0430-\u044F\u0451-]*$',
    TITLE: 'Первая буква заглавная, латиница/кириллица и дефис',
  },
  SECOND_NAME: {
    LABLE: 'Second name',
    TYPE: 'text',
    NAME: 'second_name',
    PLACEHOLDER: 'Enter second name',
    PATTERN: '^[A-Z\u0410-\u042F\u0401][\w\u0410-\u042F\u0401\u0430-\u044F\u0451-]*$',
    TITLE: 'Первая буква заглавная, латиница/кириллица и дефис',
  },
  PHONE_NUMBER: {
    LABLE: 'Phone number',
    TYPE: 'tel',
    NAME: 'phone',
    PLACEHOLDER: 'Enter phone number',
    PATTERN: '^[+]{0,1}[0-9]{10,15}$',
    TITLE: 'Цифры и плюс в начале, длина от 10 до 15',
  },
  PASSWORD: {
    LABLE: 'Password',
    TYPE: 'password',
    NAME: 'password',
    PLACEHOLDER: 'Enter password',
    PATTERN: '^(?=.*\d)(?=.*[A-Z]).{8,40}$',
    TITLE: 'от 8 до 40 символов, одна заглавная буква и цифра',
  },
  REPEAT_PASSWORD: {
    LABLE: 'Repeat password',
    TYPE: 'password',
    NAME: 'repeat_password',
    PLACEHOLDER: 'Enter password',
    PATTERN: '^(?=.*\d)(?=.*[A-Z]).{8,40}$',
    TITLE: 'от 8 до 40 символов, одна заглавная буква и цифра',
  },
  SUBMIT_BUTTON: {
    LABEL: 'Sign up',
    TYPE: 'submit',
    HANDLESUBMIT_TITLE: 'SignUp Form: ',
  },
  ROUTE_BUTTON: {
    LABEL: 'Sign in',
    TYPE: 'button',
    ROUTE: 'SIGN_IN',
  },
};
